minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@toon-format/spec@4.4.0'

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2

shellEmulator: true

allowBuilds:
  '@vscode/vsce-sign': true
  keytar: false
